<template>
	<div class="loadingio-spinner-gear-u2udkeghz4c">
		<div class="ldio-5v2jzqgpvlw">
			<div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>
				<div></div>
			</div>
		</div>
	</div>
</template>

<script>
  export default {
    name: 'Preloader'
  };
</script>

<style type="text/css">
	@keyframes ldio-5v2jzqgpvlw {
		0% {
			transform: rotate(0deg)
		}
		50% {
			transform: rotate(22.5deg)
		}
		100% {
			transform: rotate(45deg)
		}
	}

	.ldio-5v2jzqgpvlw > div {
		transform-origin: 100px 100px;
		animation: ldio-5v2jzqgpvlw 0.2s infinite linear;
	}

	.ldio-5v2jzqgpvlw > div div {
		position: absolute;
		width: 22px;
		height: 152px;
		background: #93dbe9;
		left: 100px;
		top: 100px;
		transform: translate(-50%, -50%);
	}

	.ldio-5v2jzqgpvlw > div div:nth-child(1) {
		width: 120px;
		height: 120px;
		border-radius: 50%;
	}

	.ldio-5v2jzqgpvlw > div div:nth-child(6) {
		width: 80px;
		height: 80px;
		background: #ffffff;
		border-radius: 50%;
	}

	.ldio-5v2jzqgpvlw > div div:nth-child(3) {
		transform: translate(-50%, -50%) rotate(45deg)
	}

	.ldio-5v2jzqgpvlw > div div:nth-child(4) {
		transform: translate(-50%, -50%) rotate(90deg)
	}

	.ldio-5v2jzqgpvlw > div div:nth-child(5) {
		transform: translate(-50%, -50%) rotate(135deg)
	}

	.loadingio-spinner-gear-u2udkeghz4c {
		margin: auto;
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		background: #ffffff;
	}

	.ldio-5v2jzqgpvlw {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}

	.ldio-5v2jzqgpvlw div {
		box-sizing: content-box;
	}

	/* generated by https://loading.io/ */
</style>
